### PR TITLE
Update register_EU_citizen.md

### PR DESCRIPTION
**Pull request by deniesen**
Fixed Mobilepay link

### CODE REVIEW

**Comment by enryH** [comment]
so what was the issue with the link? I don't see the difference :)

**Comment by deniesen** [comment]
There was a unicode number at the end of the link, probably the slash, so I replaced the entire link. Current version takes me to a 404 page when I click it.

**Comment by enryH** [comment]
okay! I get the same error [link](https://cphbiosciencephd.github.io/info/register/EU-citizen#once-youve-got-your-nem-id). has `%E2%80%8E` at the end. Wired that the diff does not show it...

**Review by enryH — APPROVED** [review]

**Comment by enryH** [comment]
ah. So now it still doesn't work. This link would work when you build the website locally, but to set an external link you need to prefix it with `https://` in jekyll. (This was one of the link setting issues I had in my when I mentioned them...). I will add a hint on the README.

**Pull request merged**
